LICENSELEVEL ="isLicenseLevel"
USERNAME = 'userName'
#-----------------------------Broadcast jsonnames---------------
ACTCODE ='actcode'
PACTCODE ='pactcode'
TYPE = 'type'
TOPIC ='topic'
PRIORITY = 'priority'
HIGH = 'high'
MESSAGE = 'message'
BROADCAST ="Broadcast"
UPLOAD ="Upload"
#---------------------WeTalk call configs jsonnames----------------------------
GROUP = 'Group'
DEVICE = "Individual"
FRIENDLYNAME ='friendlyname'
COMPANYID = "companyId"
COMPANYCONFIGS = "companyConfigs"
ROOMID ="roomId"
IDENTIFY = "identify"
OPS = "OPS"
VIDEOCALL = "VIDEO_CALL"
ROOMTYPE = "roomType"
PEER_TO_PEER ="peer-to-peer"
TIMESTAMP = "timestamp" or "sentTime"
AGENT = "agent"
PORTAL ="PORTAL"
ACTORID ="actorId"
POLICYID = "policyId"
INFO ="Info"
SOURCEIP ="sourceIP"
ACTION ="action"
CALL_STARTED ="Video call initiated"
VIDEOCALLING = "VIDEO CALLING"
EVENT ="event"
MSG ="msg"
CALL_ENDED = "Video calling ended"
DEVICEID ="deviceId"
CALLID ="callId"
DURATION ="duration"
DATE ="date"
DISPLAYNAME ="displayName"
OPStoDEVICE ="OPS_DEVICE"
SOURCE ="source"
INITIATEDBY ="initiatedBy"
STATUS= "status"
END="Ended"
START = "Started"
CREATEDBY ="createdBy"
#--------------------Reset Password--------------------------
EMAILID ="emailId"
OTP ='otp'
NEWPSWD ='newpassword'